ncverilog \
tb_Top.v \
Top.v \
pbkdf2.v \
hmac.v \
ShiftBytes.v \
sha3/sha_top.v \
sha3/Ffunction.v \
sha3/Theta.v \
sha3/Pi.v \
sha3/Rho.v \
sha3/Chi.v \
sha3/Iota.v \
aes/AESOneRound_noloop.v \
aes/AddRoundKey.v \
aes/KeySchedule.v \
aes/AESTOP.v \
aes/MixColumn.v \
aes/ShiftRow.v \
aes/SubByte.v \
+access+r